### ISSUE TITLE
Add general protocol information to the exporter

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/livepeer-exporter#55]
### Is your feature request related to a problem? Please describe.

It would be nice to show general LivePeer protocol information to the exporter, similar to the data displayed on the https://explorer.livepeer.org/ page.

![image](https://github.com/rickstaa/livepeer-exporter/assets/17570430/d27673ec-b07f-4aaf-b2e5-e16fe1fefd46)

### TODOs

- [ ] Add daily fees paid (i.e. `livepeer_exporter_protocol_fees_paid`).
- [ ] Add daily participation rate (i.e. `livepeer_exporter_protocol_participation_rate`).
- [ ] Add daily inflation rate (i.e. `livepeer_exporter_protocol_estimated usage`).
- [ ] Add daily delegators count (i.e. `livepeer_exporter_protocol_delegators`).
- [ ] Add daily orchestrators count (i.e. `livepeer_exporter_protocol_orchestrators`).
- [ ] Current round progress (e.g. `livepeer_exporter_protocol_current_round_blocks_remaining`, `livepeer_exporter_protocol_current_round_time_remaining`, `livepeer_exporter_protocol_current_round_progress`).
- [ ] Current round fees (i.e. `livepeer_exporter_protocol_current_round_fees`).
- [ ] Current round rewards (i.e. `livepeer_exporter_protocol_current_round_rewards`).

### Describe the solution you'd like

We can fetch this information from the following endpoints:

- https://explorer.livepeer.org/api/usage
- https://explorer.livepeer.org/_next/data/xe8lg6V7gubXcRErA1lxB/orchestrators.json
- https://explorer.livepeer.org/api/current-round

**Comment by rickstaa** [comment]
While I may not personally utilize this at the moment, I'm open to incorporating it into the system if there's significant interest from the community 👍🏻. Additionally, I welcome pull requests from individuals keen on contributing this feature independently 🚀.

**Comment by rickstaa** [comment]
Some of these metrics, like the `current_round` and `inflation`, could be added to the [go-livepeer](https://github.com/livepeer/go-livepeer/blob/587feffe958e94ceb3e2bc58fc57ff221638f183/eth/client.go#L45-L124) binary monitoring system since they are already retrieved there.
